spring.application.name=natwest
spring.datasource.url=jdbc:mysql://localhost:3306/vehicleclaim
spring.datasource.username=root
spring.datasource.password=root

logging.level.com.hcl.bean=DEBUG
spring.jpa.hibernate.ddl-auto=update

zeebe.client.broker.gateway-address=127.0.0.1:26500
zeebe.client.security.plaintext=true
server.port=8080
